sudo: false
matrix:
  include:

    - env: GCC_VERSION=4.8
      addons: &gcc48
        apt:
          packages:
            - gcc-4.8
            - g++-4.8
            - valgrind
            - check
            - pkg-config
            - cmake
            - cmake-data
            - python-virtualenv
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports

    - env: GCC_VERSION=4.9
      addons: &gcc49
        apt:
          packages:
            - gcc-4.9
            - g++-4.9
            - valgrind
            - check
            - pkg-config
            - cmake
            - cmake-data
            - python-virtualenv
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports

    - env: GCC_VERSION=5
      addons: &gcc50
        apt:
          packages:
            - gcc-5
            - g++-5
            - valgrind
            - check
            - pkg-config
            - cmake
            - cmake-data
            - python-virtualenv
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports

script:
  - cd ${TRAVIS_BUILD_DIR} && tools/travis/test && tools/travis/python-test
# after_success:
#   - cd ${TRAVIS_BUILD_DIR} && tools/coverage
